name: work
version: 1.0.0+1
publish_to: none
description: 一个插件化聚合阅读器
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: 1.0.6
  flutter_inappwebview: 6.0.0
  code_text_field: 1.1.0
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_smart_dialog: 4.9.7+5
  path_provider: 2.1.3
  path: 1.9.0
  file_picker: 8.0.3
  dio: 5.4.3+1
  flutter_widget_from_html_core: ^0.14.12
  easy_rich_text: ^2.1.0
  photo_view: ^0.15.0

dev_dependencies: 
  flutter_lints: 3.0.0
  isar_generator: 3.1.0+1
  build_runner: 2.4.9
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/rules/

get_cli: 
  separator: .
  sub_folder: false

